### ISSUE TITLE
Missing Files from code download

### ISSUE THREAD

**Issue by wallaby-gopher** [brianalewine/jellyfin-docker#1]
Hello, It seems that the caddyfile/tailscale file is missing in the code download
Your tree:
.
├── README.md
├── jellyfin-local
│   └── docker-compose.yaml
├── jellyfin-server
│   ├── cache
│   └── config
└── jellyfin-tailscale
    ├── caddy
    │   ├── Caddyfile
    │   ├── config
    │   └── data
    ├── docker-compose.yaml
    └── tailscale
        └── varlib

Downloaded tree:
.
├── jellyfin-local
│   └── docker-compose.yaml
├── jellyfin-server
│   ├── cache
│   └── config
├── jellyfin-tailscale
│   └── docker-compose.yaml
└── README.md

could you please provide the missing files? Thank you!

**Comment by brianalewine** [comment]
Added the missing files!
